/*
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
 * By starting with 1 and 2, the first 10 terms will be:
 * 
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * 
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
 * find the sum of the even-valued terms.
 */


var num1 = 0,
    num2 = 1,
    fNumbers = [];

while ( num1 + num2 < 4e6 ) {

  num1 += num2;
  if ( num1 % 2 === 0) {
    fNumbers.push(num1);
  };

  num2 += num1;
  if ( num2 % 2 === 0) {
    fNumbers.push(num2);
  }

};

var sum = fNumbers.reduce(function(prev, cur){
  return prev + cur;
})

console.log(sum);